version: '3.8'

services:
  hire-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Frontend
      - "3001:3001"  # Browser Service
      - "3100:3100"  # Workflow Service
    environment:      
      # Supabase configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # API keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Workflow service configuration
      - NODE_ENV=production
      - SERVER_PORT=3100
      - STORAGE_TYPE=memory
      
      # Browser service configuration
      - CONNECTION_MODE=${CONNECTION_MODE:-cdp}  # Options: application, cdp
      - CHROME_HOST=${CHROME_HOST:-host.docker.internal}
      - CHROME_PORT=${CHROME_PORT:-9222}
      - CHROME_CDP_URL=${CHROME_CDP_URL:-} # looks like ws://host.docker.internal:9222/devtools/browser/14721d96-6cf2-40f1-a873-6150cfc33a13
      - HEADLESS=${HEADLESS:-False}
      - VIEWPORT_WIDTH=1280
      - VIEWPORT_HEIGHT=720
      - DEBUG=${DEBUG:-False}
    volumes:
      - browser_recordings:/app/browser_service/recordings
    restart: unless-stopped

volumes:
  browser_recordings: 